"""add backtest_jobs table

Revision ID: 9634c82decb2
Revises: 63bfcaa82689
Create Date: 2026-02-09 12:30:03.730522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9634c82decb2'
down_revision: Union[str, Sequence[str], None] = '63bfcaa82689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_params', sa.JSON(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('backtest_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_id'), 'backtest_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_jobs_id'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
